
TRANSACTION_CLOSED = "closed"
TRANSACTION_RESERVED = "reversed"
TRANSACTION_PENDING = "pending"

TRANSACTION_STATUS = (
    (TRANSACTION_CLOSED, "Closed"),
    (TRANSACTION_RESERVED,"Reserved"),
    (TRANSACTION_PENDING, "Pending")
)

CONVERSION_FACTOR = 100
